### ISSUE TITLE
[Feature] 8월부터 달라진 디렉토리 적용

### ISSUE THREAD

**Issue by JoungSik** [OnlineAlgorismStudy/OASM-web#14]
<img width="408" alt="스크린샷 2020-07-28 22 39 00" src="https://user-images.githubusercontent.com/6128807/88673063-23a07400-d123-11ea-941e-80268f409cab.png">

**Comment by i-am-ren** [comment]
realtime database는 현재 공사중인가요?


## 현재 
![image](https://user-images.githubusercontent.com/67572250/89293836-8b157100-d699-11ea-8827-7046daf3989a.png)

## 나중
최종적으로는 아래 처럼 구성이 되나요? 
```
-월
|
+일
|
 ㄴ + 사용자 
```

**Comment by JoungSik** [comment]
넵! DB는 공사 완료해서 리얼타임 디비에서 firebase storage로 넘어갔어요! 확인해주시면 됩니다!

<img width="1651" alt="스크린샷 2020-08-04 22 02 40" src="https://user-images.githubusercontent.com/6128807/89297039-39bbb080-d69e-11ea-9c98-b52dbfd2932e.png">

**Comment by JoungSik** [comment]
한번 더 변경 되었습니다 ㅠㅠ
@i-am-ren 

<img width="927" alt="스크린샷 2020-08-08 13 38 22" src="https://user-images.githubusercontent.com/6128807/89702461-74626900-d97c-11ea-959a-c45d37d5071c.png">
