### ISSUE TITLE
[Feature] 모든 인원 업로드 완료시에 일자에 이미지가 보여지면 어떨까요?

### ISSUE THREAD

**Issue by JWooni** [OnlineAlgorismStudy/OASM-web#7]
**기능 소개**
모든 인원 업로드 완료시 일자 클릭이벤트 부분에 이미지가 보이고 이미지 클릭시 현재의 달성확인창이 뜨게 하는걸 조심스럽게
요청드립니다 :)

**참고 자료**
이미지 파일은 따로 보내드리겠습니다.

**Comment by JoungSik** [comment]
완료 했습니다.
